image_resizer/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("resizer.urls", namespace="resizer")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resizer/urls.py
from django.urls import path

from .views import ImagesListView, ImageDetailView, UploadImageView

app_name = "resizer"

urlpatterns = [
    path('list/', ImagesListView.as_view(), name="list"),
    path('detail/<int:pk>', ImageDetailView.as_view(), name="detail"),
    path('upload/', UploadImageView.as_view(), name="upload"),
]

resizer/models.py
from django.db import models

from django.urls import reverse
# Create your models here.


class Image(models.Model):
    image = models.ImageField(upload_to="original_image", verbose_name="Не измененное изображение")

    class Meta:
        verbose_name = "Картинка"
        verbose_name_plural = "Картинки"

    def __str__(self):
        return self.image.name

    def get_absolute_url(self):
        return reverse("resizer:detail", args=[self.pk])


class ResizedImage(models.Model):
    original_image = models.OneToOneField(Image, models.CASCADE)
    resized_image = models.ImageField(upload_to="resized_image", verbose_name="Измененное изображение", null=True, blank=True)

    class Meta:
        verbose_name = "Измененная картинка"
        verbose_name_plural = "Измененные картинки"

    def __str__(self):
        return self.resized_image.name

resizer/forms.py
from django import forms

class SizeForm(forms.Form):
    height = forms.IntegerField(required=False)
    width = forms.IntegerField(required=False)

class UploadForm(forms.Form):
    url = forms.URLField(required=False)
    image = forms.ImageField(required=False)

resizer/views.py
import requests

from PIL import Image as PilImage

from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, FormView

from django.urls import reverse

from django.core.files.base import ContentFile
from django.core.exceptions import ObjectDoesNotExist

from .models import Image, ResizedImage
from .forms import SizeForm, UploadForm
# Create your views here.


class ImageMixin:
    def get_image_name(self, path: str = None) -> str:
        if not path:
            image = get_object_or_404(Image, pk=self.kwargs["pk"])
            path = image.image.name
        return path[path.rfind('/') + 1:]

    def resize_image(self, width, height):
        image: Image = get_object_or_404(Image, pk=self.kwargs["pk"])
        image_content: ContentFile = ContentFile(image.image.read())
        resized_image: ResizedImage = ResizedImage.objects.update_or_create(original_image=image)[0]
        resized_image.resized_image.save(name=self.get_image_name(),
                                         content=image_content)

        pil_image = PilImage.open(resized_image.resized_image.path)
        pil_image = pil_image.resize((width, height))
        pil_image.save(resized_image.resized_image.path)
        return resized_image

    def get_context_sizes(self) -> dict:
        image: Image = get_object_or_404(Image, pk=self.kwargs["pk"])
        try:
            return {
                "width": image.resizedimage.resized_image.width,
                "height": image.resizedimage.resized_image.height
            }

        except ObjectDoesNotExist:
            return {
                "width": image.image.width,
                "height": image.image.height
            }

    def save_image_from_url(self, url: str) -> Image:
        binary_content: bytes = requests.get(url).content
        image_content: ContentFile = ContentFile(binary_content)
        image = Image.objects.create()
        image.image.save(name=self.get_image_name(url),
                         content=image_content)
        return image


class ImagesListView(ListView):
    template_name = "resizer/list.html"
    context_object_name = "images"
    model = Image


class ImageDetailView(FormView, ImageMixin):
    template_name = "resizer/detail.html"
    form_class = SizeForm

    def form_valid(self, form):
        self.success_url = reverse("resizer:detail", args=[self.kwargs["pk"]])
        context_sizes = self.get_context_sizes()
        width: int = form.cleaned_data["width"] or context_sizes["width"]
        height: int = form.cleaned_data["height"] or context_sizes["height"]
        self.resize_image(width, height)
        return super(ImageDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["image"] = get_object_or_404(Image, pk=self.kwargs["pk"])
        return context


class UploadImageView(FormView, ImageMixin):
    template_name = "resizer/upload.html"
    form_class = UploadForm

    def form_valid(self, form, **kwargs):
        if form.cleaned_data["url"] and form.cleaned_data["image"]:
            context = super().get_context_data(**kwargs)
            context["error"]: str = "Нужно ввести только одно поле"
            return render(self.request, self.template_name, context)

        if form.cleaned_data["url"]:
            image: Image = self.save_image_from_url(form.cleaned_data["url"])
            self.success_url = reverse("resizer:detail", args=[image.pk])
            return super().form_valid(form)

        print(form.files)
        if form.cleaned_data["image"]:
            image = Image()
            image.image = form.cleaned_data["image"]
            image.save()
            print("here")
            self.success_url = reverse("resizer:detail", args=[image.pk])
            return super().form_valid(form)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
        <title>Not implemented TITLE block</title>
    {% endblock %}
</head>
<body>
    {% block content %}
        <title>Not implemented CONTENT block</title>
    {% endblock %}
</body>
</html>

templates/resizer/detail.html
{% extends "base.html" %}

{% block title %}
    <title>Image detail -> {{ object.pk }}</title>
{% endblock %}

{% block content %}
    <a href="{% url 'resizer:list' %}">Назад к списку</a>
    <h2>{{ image.image }}</h2>

    {% if image.resizedimage %}

    <form action="" method="post">
        {% csrf_token %}
        <label for="width">Ширина</label> <br>
        <input type="text" id="width" name="width" placeholder="{{ image.resizedimage.resized_image.width }}"> <br>
        <label for="height">Высота</label> <br>
        <input type="text" id="height" name="height" placeholder="{{ image.resizedimage.resized_image.height }}"> <br>
        <button type="submit">Отправить</button>
    </form>

    <img src="{{ image.resizedimage.resized_image.url }}" alt="">
    {% else %}

    <form action="" method="post">
        {% csrf_token %}
        <label for="width">Ширина</label> <br>
        <input type="text" id="width" name="width" placeholder="{{ image.image.width }}"> <br>
        <label for="height">Высота</label> <br>
        <input type="text" id="height" name="height" placeholder="{{ image.image.height }}"> <br>
        <button type="submit">Отправить</button>
    </form>

    <img src="{{ image.image.url }}" alt="">
    {% endif %}

{% endblock %}

templates/resizer/list.html
{% extends "base.html" %}


{% block title %}
    <title>Images -> List</title>
{% endblock %}

{% block content %}
    <h1>Список изображений</h1>
    {% if images %}
        {% for image in images %}
            <a href="{% url 'resizer:detail' pk=image.pk %}">{{ image }}</a> <br>
        {% endfor %}
    {% else %}
        <br>
        <p>Нет доступных изображений</p>
    {% endif %}
    <a href="{% url 'resizer:upload' %}">Добавить изображение</a>
{% endblock %}

templates/resizer/upload.html
{% extends "base.html" %}

{% block title %}
    <title>Image -> Upload</title>
{% endblock %}

{% block content %}
    <a href="{% url 'resizer:list' %}">Назад к списку</a>

    {% if error %}
         <h2>{{ error }}</h2>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}